version: '3'
services:
    client:
        container_name: client_ati
        volumes:
            - ./Frontend:/usr/src/app
        restart: always
        build: ./Frontend
        ports: 
            - '5000:5001'
        environment:
            APP_DEBUG: "True"
            APP_ENV: "dev"
            APP_PORT: 5001
            MONGO_URI: "mongodb://mongo:27017/ati-te-educamos"
        depends_on:
            - db
        links:
            - db 
        #     - server
    # server:
    #     container_name: backend_ati
    #     volumes:
    #         - ./Backend:/usr/src/app
    #     restart: always
    #     build: ./Backend
    #     ports: 
    #         - '81:5000'
    #     links:
    #         - db
    db:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
        # networks: 
        #     - default


# networks:
#     frontend:
#         driver: bridge
#     backend:
#         driver: bridge

# volumes:
#     mongodbdata:
#         driver: local
#     appdata:
#         driver: local

